/** Auto-generated by scripts/generate-insync-cards.mjs — do not edit by hand */
import type { InSyncCard } from './types';

export const INSYNC_CARDS: InSyncCard[] = [
	{
		id: 'underrated-overrated',
		category: 'general',
		left: { en: "Underrated", da: "Undervurderet" },
		right: { en: "Overrated", da: "Overvurderet" }
	},
	{
		id: 'harmless-dangerous',
		category: 'general',
		left: { en: "Harmless", da: "Ufarlig" },
		right: { en: "Dangerous", da: "Farlig" }
	},
	{
		id: 'not-intimidating-very-intimidating',
		category: 'general',
		left: { en: "Not intimidating", da: "Ikke intimiderende" },
		right: { en: "Very intimidating", da: "Meget intimiderende" }
	},
	{
		id: 'low-effort-high-effort',
		category: 'general',
		left: { en: "Low effort", da: "Lav indsats" },
		right: { en: "High effort", da: "Høj indsats" }
	},
	{
		id: 'cheap-looking-expensive-looking',
		category: 'general',
		left: { en: "Cheap-looking", da: "Ser billigt ud" },
		right: { en: "Expensive-looking", da: "Ser dyrt ud" }
	},
	{
		id: 'easy-to-explain-hard-to-explain',
		category: 'general',
		left: { en: "Easy to explain", da: "Let at forklare" },
		right: { en: "Hard to explain", da: "Svær at forklare" }
	},
	{
		id: 'forgettable-iconic',
		category: 'general',
		left: { en: "Forgettable", da: "Glemt i morgen" },
		right: { en: "Iconic", da: "Ikonisk" }
	},
	{
		id: 'normal-unhinged',
		category: 'general',
		left: { en: "Normal", da: "Normal" },
		right: { en: "Unhinged", da: "Skør" }
	},
	{
		id: 'boring-exciting',
		category: 'general',
		left: { en: "Boring", da: "Kedelig" },
		right: { en: "Exciting", da: "Spændende" }
	},
	{
		id: 'innocent-suspicious',
		category: 'general',
		left: { en: "Innocent", da: "Uskyldig" },
		right: { en: "Suspicious", da: "Mistænkelig" }
	},
	{
		id: 'childish-mature',
		category: 'general',
		left: { en: "Childish", da: "Barnlig" },
		right: { en: "Mature", da: "Moden" }
	},
	{
		id: 'practical-ridiculous',
		category: 'general',
		left: { en: "Practical", da: "Praktisk" },
		right: { en: "Ridiculous", da: "Latterlig" }
	},
	{
		id: 'predictable-surprising',
		category: 'general',
		left: { en: "Predictable", da: "Forudsigelig" },
		right: { en: "Surprising", da: "Overraskende" }
	},
	{
		id: 'low-risk-high-risk',
		category: 'general',
		left: { en: "Low risk", da: "Lav risiko" },
		right: { en: "High risk", da: "Høj risiko" }
	},
	{
		id: 'polite-rude',
		category: 'general',
		left: { en: "Polite", da: "Høflig" },
		right: { en: "Rude", da: "Uhøflig" }
	},
	{
		id: 'subtle-obvious',
		category: 'general',
		left: { en: "Subtle", da: "Subtil" },
		right: { en: "Obvious", da: "Tydelig" }
	},
	{
		id: 'relaxing-stressful',
		category: 'general',
		left: { en: "Relaxing", da: "Afslappende" },
		right: { en: "Stressful", da: "Stressende" }
	},
	{
		id: 'simple-complicated',
		category: 'general',
		left: { en: "Simple", da: "Simpel" },
		right: { en: "Complicated", da: "Kompliceret" }
	},
	{
		id: 'cute-creepy',
		category: 'general',
		left: { en: "Cute", da: "Nuttet" },
		right: { en: "Creepy", da: "Uhyggelig" }
	},
	{
		id: 'wholesome-cursed',
		category: 'general',
		left: { en: "Wholesome", da: "Hyggelig" },
		right: { en: "Cursed", da: "Forbandet" }
	},
	{
		id: 'green-flag-red-flag',
		category: 'social',
		left: { en: "Green flag", da: "Grønt flag" },
		right: { en: "Red flag", da: "Rødt flag" }
	},
	{
		id: 'reasonable-favor-huge-ask',
		category: 'social',
		left: { en: "Reasonable favor", da: "Fornuftig tjeneste" },
		right: { en: "Huge ask", da: "Kæmpe tjeneste" }
	},
	{
		id: 'good-excuse-bad-excuse',
		category: 'social',
		left: { en: "Good excuse", da: "God undskyldning" },
		right: { en: "Bad excuse", da: "Dårlig undskyldning" }
	},
	{
		id: 'fine-to-say-keep-to-yourself',
		category: 'social',
		left: { en: "Fine to say out loud", da: "Okay at sige højt" },
		right: { en: "Keep that to yourself", da: "Hold det for dig selv" }
	},
	{
		id: 'small-talk-deep-conversation',
		category: 'social',
		left: { en: "Small talk topic", da: "Smalltalk-emne" },
		right: { en: "Deep conversation topic", da: "Dyb samtale" }
	},
	{
		id: 'private-thought-public-announcement',
		category: 'social',
		left: { en: "Private thought", da: "Privat tanke" },
		right: { en: "Public announcement", da: "Offentlig meddelelse" }
	},
	{
		id: 'slightly-awkward-painfully-awkward',
		category: 'social',
		left: { en: "Slightly awkward", da: "Lidt akavet" },
		right: { en: "Painfully awkward", da: "Pinligt akavet" }
	},
	{
		id: 'acceptable-lie-unforgivable-lie',
		category: 'social',
		left: { en: "Acceptable lie", da: "Acceptabel løgn" },
		right: { en: "Unforgivable lie", da: "Utilgivelig løgn" }
	},
	{
		id: 'friendly-flirty',
		category: 'social',
		left: { en: "Friendly", da: "Venlig" },
		right: { en: "Flirty", da: "Flirtende" }
	},
	{
		id: 'confident-arrogant',
		category: 'social',
		left: { en: "Confident", da: "Selvsikker" },
		right: { en: "Arrogant", da: "Arrogant" }
	},
	{
		id: 'honest-too-honest',
		category: 'social',
		left: { en: "Honest", da: "Ærlig" },
		right: { en: "Too honest", da: "For ærlig" }
	},
	{
		id: 'cute-habit-annoying-habit',
		category: 'social',
		left: { en: "Cute habit", da: "Sød vane" },
		right: { en: "Annoying habit", da: "Irriterende vane" }
	},
	{
		id: 'good-listener-conversation-hijacker',
		category: 'social',
		left: { en: "Good listener", da: "God lytter" },
		right: { en: "Conversation hijacker", da: "Samtale-kaprer" }
	},
	{
		id: 'low-maintenance-high-maintenance-friend',
		category: 'social',
		left: { en: "Low-maintenance friend", da: "Nem ven" },
		right: { en: "High-maintenance friend", da: "Krævende ven" }
	},
	{
		id: 'textable-issue-phone-call-issue',
		category: 'social',
		left: { en: "Textable issue", da: "Kan sms'es om" },
		right: { en: "Phone-call issue", da: "Kræver telefonopkald" }
	},
	{
		id: 'normal-message-concerning-message',
		category: 'social',
		left: { en: "Normal message", da: "Normal besked" },
		right: { en: "Concerning message", da: "Bekymrende besked" }
	},
	{
		id: 'worth-apologizing-not-worth-apologizing',
		category: 'social',
		left: { en: "Worth apologizing for", da: "Værd at undskylde" },
		right: { en: "Not worth apologizing for", da: "Ikke værd at undskylde" }
	},
	{
		id: 'forgivable-mistake-relationship-ending',
		category: 'social',
		left: { en: "Forgivable mistake", da: "Tilgivelig fejl" },
		right: { en: "Relationship-ending mistake", da: "Forholds-dræber" }
	},
	{
		id: 'good-party-guest-bad-party-guest',
		category: 'social',
		left: { en: "Good party guest", da: "God festgæst" },
		right: { en: "Bad party guest", da: "Dårlig festgæst" }
	},
	{
		id: 'knows-vibe-ruins-vibe',
		category: 'social',
		left: { en: "Knows the vibe", da: "Forstår stemningen" },
		right: { en: "Ruins the vibe", da: "Ødelægger stemningen" }
	},
	{
		id: 'breakfast-dinner-food',
		category: 'food',
		left: { en: "Breakfast food", da: "Morgenmad" },
		right: { en: "Dinner food", da: "Aftensmad" }
	},
	{
		id: 'snack-meal',
		category: 'food',
		left: { en: "Snack", da: "Snack" },
		right: { en: "Meal", da: "Måltid" }
	},
	{
		id: 'comfort-food-punishment-food',
		category: 'food',
		left: { en: "Comfort food", da: "Trøstemad" },
		right: { en: "Punishment food", da: "Straffemad" }
	},
	{
		id: 'kid-food-adult-food',
		category: 'food',
		left: { en: "Kid food", da: "Børnemad" },
		right: { en: "Adult food", da: "Voksenmad" }
	},
	{
		id: 'mess-free-extremely-messy',
		category: 'food',
		left: { en: "Mess-free", da: "Intet svineri" },
		right: { en: "Extremely messy", da: "Ekstremt svineri" }
	},
	{
		id: 'worth-mess-not-worth-mess',
		category: 'food',
		left: { en: "Worth the mess", da: "Svineriet værd" },
		right: { en: "Not worth the mess", da: "Ikke svineriet værd" }
	},
	{
		id: 'bland-intense',
		category: 'food',
		left: { en: "Bland", da: "Smagsløs" },
		right: { en: "Intense", da: "Intens" }
	},
	{
		id: 'dry-saucy',
		category: 'food',
		left: { en: "Dry", da: "Tør" },
		right: { en: "Saucy", da: "Masser af sovs" }
	},
	{
		id: 'light-meal-food-coma',
		category: 'food',
		left: { en: "Light meal", da: "Let måltid" },
		right: { en: "Food coma", da: "Madkoma" }
	},
	{
		id: 'cheap-order-fancy-order',
		category: 'food',
		left: { en: "Cheap restaurant order", da: "Billig bestilling" },
		right: { en: "Fancy restaurant order", da: "Fancy bestilling" }
	},
	{
		id: 'safe-menu-risky-menu',
		category: 'food',
		left: { en: "Safe menu choice", da: "Sikkert valg" },
		right: { en: "Risky menu choice", da: "Risikabelt valg" }
	},
	{
		id: 'good-cold-only-good-hot',
		category: 'food',
		left: { en: "Good cold", da: "God kold" },
		right: { en: "Only good hot", da: "Kun god varm" }
	},
	{
		id: 'overpriced-worth-price',
		category: 'food',
		left: { en: "Overpriced", da: "Overpris" },
		right: { en: "Worth the price", da: "Pengene værd" }
	},
	{
		id: 'fake-tasting-natural-tasting',
		category: 'food',
		left: { en: "Fake-tasting", da: "Smager kunstigt" },
		right: { en: "Natural-tasting", da: "Smager naturligt" }
	},
	{
		id: 'looks-bad-tastes-good-looks-good-tastes-bad',
		category: 'food',
		left: { en: "Looks bad, tastes good", da: "Ser skidt ud, smager godt" },
		right: { en: "Looks good, tastes bad", da: "Ser godt ud, smager dårligt" }
	},
	{
		id: 'bad-airplane-food-good-airplane-food',
		category: 'food',
		left: { en: "Bad airplane food", da: "Dårlig flymad" },
		right: { en: "Good airplane food", da: "God flymad" }
	},
	{
		id: 'easy-share-awful-share',
		category: 'food',
		left: { en: "Easy to share", da: "Nem at dele" },
		right: { en: "Awful to share", da: "Forfærdelig at dele" }
	},
	{
		id: 'everyday-drink-special-occasion',
		category: 'food',
		left: { en: "Everyday drink", da: "Hverdagsdrik" },
		right: { en: "Special occasion drink", da: "Festdrik" }
	},
	{
		id: 'mild-painfully-spicy',
		category: 'food',
		left: { en: "Mild", da: "Mild" },
		right: { en: "Painfully spicy", da: "Smertefuldt stærk" }
	},
	{
		id: 'needs-topping-perfect-as-is',
		category: 'food',
		left: { en: "Needs a topping", da: "Skal have topping" },
		right: { en: "Perfect as-is", da: "Perfekt som den er" }
	},
	{
		id: 'guilty-pleasure-respectable-taste',
		category: 'pop',
		left: { en: "Guilty pleasure", da: "Guilty pleasure" },
		right: { en: "Respectable taste", da: "Respektabel smag" }
	},
	{
		id: 'background-noise-must-watch',
		category: 'pop',
		left: { en: "Background noise", da: "Baggrundsstøj" },
		right: { en: "Must-watch", da: "Skal ses" }
	},
	{
		id: 'cult-classic-mainstream-hit',
		category: 'pop',
		left: { en: "Cult classic", da: "Kultklassiker" },
		right: { en: "Mainstream hit", da: "Mainstream-hit" }
	},
	{
		id: 'aged-badly-aged-well',
		category: 'pop',
		left: { en: "Aged badly", da: "Aldret dårligt" },
		right: { en: "Aged well", da: "Aldret godt" }
	},
	{
		id: 'bad-sequel-great-sequel',
		category: 'pop',
		left: { en: "Bad sequel idea", da: "Dårlig efterfølger-idé" },
		right: { en: "Great sequel idea", da: "God efterfølger-idé" }
	},
	{
		id: 'skip-intro-never-skip-intro',
		category: 'pop',
		left: { en: "Skip the intro", da: "Spring intro over" },
		right: { en: "Never skip the intro", da: "Aldrig spring intro over" }
	},
	{
		id: 'one-hit-wonder-legendary-career',
		category: 'pop',
		left: { en: "One-hit wonder", da: "One-hit wonder" },
		right: { en: "Legendary career", da: "Legendarisk karriere" }
	},
	{
		id: 'niche-fandom-everyone-knows',
		category: 'pop',
		left: { en: "Niche fandom", da: "Niche-fandom" },
		right: { en: "Everyone knows it", da: "Alle kender det" }
	},
	{
		id: 'cringe-cool',
		category: 'pop',
		left: { en: "Cringe", da: "Cringe" },
		right: { en: "Cool", da: "Cool" }
	},
	{
		id: 'try-hard-effortlessly-cool',
		category: 'pop',
		left: { en: "Try-hard", da: "Prøver for hårdt" },
		right: { en: "Effortlessly cool", da: "Cool uden at prøve" }
	},
	{
		id: 'low-budget-blockbuster',
		category: 'pop',
		left: { en: "Low-budget energy", da: "Lavbudget-energi" },
		right: { en: "Blockbuster energy", da: "Blockbuster-energi" }
	},
	{
		id: 'bad-karaoke-great-karaoke',
		category: 'pop',
		left: { en: "Bad karaoke choice", da: "Dårligt karaokevalg" },
		right: { en: "Great karaoke choice", da: "Godt karaokevalg" }
	},
	{
		id: 'bad-wedding-song-great-wedding-song',
		category: 'pop',
		left: { en: "Bad wedding song", da: "Dårlig bryllupssang" },
		right: { en: "Great wedding song", da: "God bryllupssang" }
	},
	{
		id: 'memeable-not-memeable',
		category: 'pop',
		left: { en: "Memeable", da: "Meme-værdig" },
		right: { en: "Not memeable", da: "Ikke meme-værdig" }
	},
	{
		id: 'villain-coded-hero-coded',
		category: 'pop',
		left: { en: "Villain-coded", da: "Skurk-energi" },
		right: { en: "Hero-coded", da: "Helt-energi" }
	},
	{
		id: 'side-character-main-character',
		category: 'pop',
		left: { en: "Side character energy", da: "Birolle-energi" },
		right: { en: "Main character energy", da: "Hovedrolle-energi" }
	},
	{
		id: 'forgettable-villain-iconic-villain',
		category: 'pop',
		left: { en: "Forgettable villain", da: "Glemt skurk" },
		right: { en: "Iconic villain", da: "Ikonisk skurk" }
	},
	{
		id: 'bad-reality-show-great-reality-show',
		category: 'pop',
		left: { en: "Bad reality show idea", da: "Dårlig reality-idé" },
		right: { en: "Great reality show idea", da: "God reality-idé" }
	},
	{
		id: 'needs-reboot-leave-alone',
		category: 'pop',
		left: { en: "Needs a reboot", da: "Trænger til reboot" },
		right: { en: "Leave it alone", da: "Lad den være" }
	},
	{
		id: 'flop-today-still-hit',
		category: 'pop',
		left: { en: "Would flop today", da: "Floppede i dag" },
		right: { en: "Would still be a hit", da: "Stadig et hit" }
	},
	{
		id: 'easy-class-impossible-class',
		category: 'life',
		left: { en: "Easy class", da: "Let fag" },
		right: { en: "Impossible class", da: "Umuligt fag" }
	},
	{
		id: 'fake-job-real-job',
		category: 'life',
		left: { en: "Fake-sounding job", da: "Lyder opdigtet" },
		right: { en: "Real-sounding job", da: "Lyder ægte" }
	},
	{
		id: 'useless-skill-essential-skill',
		category: 'life',
		left: { en: "Useless skill", da: "Ubrugelig færdighed" },
		right: { en: "Essential skill", da: "Essentiel færdighed" }
	},
	{
		id: 'not-resume-very-resume',
		category: 'life',
		left: { en: "Not résumé-worthy", da: "Hører ikke hjemme på CV" },
		right: { en: "Very résumé-worthy", da: "Hører hjemme på CV" }
	},
	{
		id: 'dream-job-nightmare-job',
		category: 'life',
		left: { en: "Dream job", da: "Drømmejob" },
		right: { en: "Nightmare job", da: "Mareridtsjob" }
	},
	{
		id: 'minor-inconvenience-day-ruining',
		category: 'life',
		left: { en: "Minor inconvenience", da: "Lille irritationsmoment" },
		right: { en: "Day-ruining inconvenience", da: "Ødelægger hele dagen" }
	},
	{
		id: 'productive-fake-productive',
		category: 'life',
		left: { en: "Productive", da: "Produktiv" },
		right: { en: "Fake productive", da: "Fake produktiv" }
	},
	{
		id: 'good-meeting-could-be-email',
		category: 'life',
		left: { en: "Good meeting topic", da: "Godt mødeemne" },
		right: { en: "Could have been an email", da: "Kunne have været en mail" }
	},
	{
		id: 'casual-signoff-formal-signoff',
		category: 'life',
		left: { en: "Casual email sign-off", da: "Afslappet mail-afsked" },
		right: { en: "Formal email sign-off", da: "Formel mail-afsked" }
	},
	{
		id: 'underpaid-overpaid',
		category: 'life',
		left: { en: "Underpaid", da: "Underbetalt" },
		right: { en: "Overpaid", da: "Overbetalt" }
	},
	{
		id: 'beginner-friendly-expert-only',
		category: 'life',
		left: { en: "Beginner-friendly", da: "Begynder-venlig" },
		right: { en: "Expert-only", da: "Kun for eksperter" }
	},
	{
		id: 'easy-fake-impossible-fake',
		category: 'life',
		left: { en: "Easy to fake", da: "Let at fake" },
		right: { en: "Impossible to fake", da: "Umuligt at fake" }
	},
	{
		id: 'low-pressure-high-pressure-decision',
		category: 'life',
		left: { en: "Low-pressure decision", da: "Beslutning uden pres" },
		right: { en: "High-pressure decision", da: "Beslutning under pres" }
	},
	{
		id: 'good-use-money-cry-for-help',
		category: 'life',
		left: { en: "Good use of money", da: "God brug af penge" },
		right: { en: "Financial cry for help", da: "Økonomisk nødråb" }
	},
	{
		id: 'worth-waking-up-not-worth',
		category: 'life',
		left: { en: "Worth waking up early for", da: "Værd at stå tidligt op for" },
		right: { en: "Not worth waking up early for", da: "Ikke værd at stå tidligt op for" }
	},
	{
		id: 'tiny-problem-actual-emergency',
		category: 'life',
		left: { en: "Tiny problem", da: "Lille problem" },
		right: { en: "Actual emergency", da: "Rigtig nødsituation" }
	},
	{
		id: 'fun-chore-soul-crushing-chore',
		category: 'life',
		left: { en: "Fun chore", da: "Sjov pligt" },
		right: { en: "Soul-crushing chore", da: "Sjæleknusende pligt" }
	},
	{
		id: 'good-habit-bad-habit',
		category: 'life',
		left: { en: "Good habit", da: "God vane" },
		right: { en: "Bad habit", da: "Dårlig vane" }
	},
	{
		id: 'temporary-phase-personality-trait',
		category: 'life',
		left: { en: "Temporary phase", da: "Midlertidig fase" },
		right: { en: "Personality trait", da: "Personlighedstræk" }
	},
	{
		id: 'responsible-reckless',
		category: 'life',
		left: { en: "Responsible", da: "Ansvarlig" },
		right: { en: "Reckless", da: "Uansvarlig" }
	},
	{
		id: 'bedroom-museum',
		category: 'places',
		left: { en: "Belongs in a bedroom", da: "Hører hjemme på soveværelset" },
		right: { en: "Belongs in a museum", da: "Hører hjemme på museum" }
	},
	{
		id: 'normal-own-weird-own',
		category: 'places',
		left: { en: "Normal thing to own", da: "Normalt at eje" },
		right: { en: "Weird thing to own", da: "Mærkeligt at eje" }
	},
	{
		id: 'useful-decorative',
		category: 'places',
		left: { en: "Useful object", da: "Nyttig ting" },
		right: { en: "Decorative object", da: "Pynteting" }
	},
	{
		id: 'cheap-gift-thoughtful-gift',
		category: 'places',
		left: { en: "Cheap gift", da: "Billig gave" },
		right: { en: "Thoughtful gift", da: "Gennemtænkt gave" }
	},
	{
		id: 'good-souvenir-bad-souvenir',
		category: 'places',
		left: { en: "Good souvenir", da: "God souvenir" },
		right: { en: "Bad souvenir", da: "Dårlig souvenir" }
	},
	{
		id: 'clean-place-gross-place',
		category: 'places',
		left: { en: "Clean place", da: "Rent sted" },
		right: { en: "Gross place", da: "Ulækkert sted" }
	},
	{
		id: 'peaceful-chaotic-place',
		category: 'places',
		left: { en: "Peaceful place", da: "Fredeligt sted" },
		right: { en: "Chaotic place", da: "Kaotisk sted" }
	},
	{
		id: 'good-first-date-bad-first-date',
		category: 'places',
		left: { en: "Good first-date location", da: "Godt første-date-sted" },
		right: { en: "Bad first-date location", da: "Dårligt første-date-sted" }
	},
	{
		id: 'good-cry-bad-cry',
		category: 'places',
		left: { en: "Good place to cry", da: "Godt sted at græde" },
		right: { en: "Bad place to cry", da: "Dårligt sted at græde" }
	},
	{
		id: 'good-nap-terrible-nap',
		category: 'places',
		left: { en: "Good place to nap", da: "Godt sted at tage en lur" },
		right: { en: "Terrible place to nap", da: "Forfærdeligt sted at tage en lur" }
	},
	{
		id: 'public-behavior-private-behavior',
		category: 'places',
		left: { en: "Public place behavior", da: "Offentlig opførsel" },
		right: { en: "Private place behavior", da: "Privat opførsel" }
	},
	{
		id: 'safe-hiding-terrible-hiding',
		category: 'places',
		left: { en: "Safe hiding spot", da: "Godt skjulested" },
		right: { en: "Terrible hiding spot", da: "Forfærdeligt skjulested" }
	},
	{
		id: 'cozy-sterile',
		category: 'places',
		left: { en: "Cozy", da: "Hyggelig" },
		right: { en: "Sterile", da: "Steril" }
	},
	{
		id: 'inviting-hostile',
		category: 'places',
		left: { en: "Inviting", da: "Indbydende" },
		right: { en: "Hostile", da: "Fjendtlig" }
	},
	{
		id: 'too-empty-too-crowded',
		category: 'places',
		left: { en: "Too empty", da: "For tomt" },
		right: { en: "Too crowded", da: "For overfyldt" }
	},
	{
		id: 'looks-haunted-looks-normal',
		category: 'places',
		left: { en: "Looks haunted", da: "Ser hjemsøgt ud" },
		right: { en: "Looks aggressively normal", da: "Ser aggressivt normal ud" }
	},
	{
		id: 'vacation-errand-spot',
		category: 'places',
		left: { en: "Vacation spot", da: "Feriested" },
		right: { en: "Errand spot", da: "Ærinde-sted" }
	},
	{
		id: 'romantic-unromantic',
		category: 'places',
		left: { en: "Romantic place", da: "Romantisk sted" },
		right: { en: "Unromantic place", da: "Uromantisk sted" }
	},
	{
		id: 'good-bathroom-bad-bathroom',
		category: 'places',
		left: { en: "Good bathroom", da: "Godt toilet" },
		right: { en: "Bad bathroom", da: "Dårligt toilet" }
	},
	{
		id: 'worth-waiting-not-worth-waiting',
		category: 'places',
		left: { en: "Worth waiting in line for", da: "Værd at stå i kø for" },
		right: { en: "Not worth waiting in line for", da: "Ikke værd at stå i kø for" }
	},
	{
		id: 'little-cursed-deeply-cursed',
		category: 'weird',
		left: { en: "A little cursed", da: "Lidt forbandet" },
		right: { en: "Deeply cursed", da: "Dybt forbandet" }
	},
	{
		id: 'goblin-royalty',
		category: 'weird',
		left: { en: "Goblin energy", da: "Goblin-energi" },
		right: { en: "Royalty energy", da: "Kongelig energi" }
	},
	{
		id: 'human-robot',
		category: 'weird',
		left: { en: "Human behavior", da: "Menneske-adfærd" },
		right: { en: "Robot behavior", da: "Robot-adfærd" }
	},
	{
		id: 'wizard-accountant',
		category: 'weird',
		left: { en: "Wizard behavior", da: "Troldmand-adfærd" },
		right: { en: "Accountant behavior", da: "Revisor-adfærd" }
	},
	{
		id: 'normal-collection-concerning-collection',
		category: 'weird',
		left: { en: "Normal collection", da: "Normal samling" },
		right: { en: "Concerning collection", da: "Bekymrende samling" }
	},
	{
		id: 'normal-pockets-too-many-pockets',
		category: 'weird',
		left: { en: "Normal amount of pockets", da: "Normalt antal lommer" },
		right: { en: "Too many pockets", da: "For mange lommer" }
	},
	{
		id: 'tiny-animal-large-animal',
		category: 'weird',
		left: { en: "Tiny animal energy", da: "Smådyr-energi" },
		right: { en: "Large animal energy", da: "Stordyr-energi" }
	},
	{
		id: 'scared-of-goose-goose-scared',
		category: 'weird',
		left: { en: "Would be scared of a goose", da: "Ville være bange for en gås" },
		right: { en: "A goose would be scared of them", da: "En gås ville være bange for dem" }
	},
	{
		id: 'looks-edible-not-edible',
		category: 'weird',
		left: { en: "Looks edible", da: "Ser spiselig ud" },
		right: { en: "Definitely not edible", da: "Bestemt ikke spiselig" }
	},
	{
		id: 'pet-name-villain-name',
		category: 'weird',
		left: { en: "Could be a pet name", da: "Kunne være kæledyrsnavn" },
		right: { en: "Could be a villain name", da: "Kunne være skurkenavn" }
	},
	{
		id: 'normal-whisper-terrifying-whisper',
		category: 'weird',
		left: { en: "Normal thing to whisper", da: "Normalt at hviske" },
		right: { en: "Terrifying thing to whisper", da: "Skræmmende at hviske" }
	},
	{
		id: 'not-suspicious-buy-very-suspicious-buy',
		category: 'weird',
		left: { en: "Not suspicious to buy", da: "Ikke mistænkeligt at købe" },
		right: { en: "Very suspicious to buy", da: "Meget mistænkeligt at købe" }
	},
	{
		id: 'good-omen-bad-omen',
		category: 'weird',
		left: { en: "Good omen", da: "Godt varsel" },
		right: { en: "Bad omen", da: "Dårligt varsel" }
	},
	{
		id: 'fairy-tale-crime-scene',
		category: 'weird',
		left: { en: "Fairy tale object", da: "Eventyr-genstand" },
		right: { en: "Crime scene object", da: "Gerningssted-genstand" }
	},
	{
		id: 'magic-item-office-supply',
		category: 'weird',
		left: { en: "Magic item", da: "Magisk genstand" },
		right: { en: "Office supply", da: "Kontorartikel" }
	},
	{
		id: 'haunted-doll-golden-retriever',
		category: 'weird',
		left: { en: "Haunted doll energy", da: "Hjemsøgt dukke-energi" },
		right: { en: "Golden retriever energy", da: "Golden retriever-energi" }
	},
	{
		id: 'cryptid-influencer',
		category: 'weird',
		left: { en: "Cryptid behavior", da: "Cryptid-adfærd" },
		right: { en: "Influencer behavior", da: "Influencer-adfærd" }
	},
	{
		id: 'normal-dream-nightmare',
		category: 'weird',
		left: { en: "Normal dream", da: "Normal drøm" },
		right: { en: "Nightmare", da: "Mareridt" }
	},
	{
		id: 'cute-chaos-bad-chaos',
		category: 'weird',
		left: { en: "Cute chaos", da: "Sødt kaos" },
		right: { en: "Bad chaos", da: "Dårligt kaos" }
	},
	{
		id: 'childrens-book-horror-movie',
		category: 'weird',
		left: { en: "Would survive in a children's book", da: "Overlever i børnebog" },
		right: { en: "Would survive in a horror movie", da: "Overlever i gyserfilm" }
	},
	{
		id: 'art-not-art',
		category: 'debate',
		left: { en: "Art", da: "Kunst" },
		right: { en: "Not art", da: "Ikke kunst" }
	},
	{
		id: 'sport-not-sport',
		category: 'debate',
		left: { en: "Sport", da: "Sport" },
		right: { en: "Not a sport", da: "Ikke en sport" }
	},
	{
		id: 'sandwich-not-sandwich',
		category: 'debate',
		left: { en: "Sandwich", da: "Sandwich" },
		right: { en: "Not a sandwich", da: "Ikke en sandwich" }
	},
	{
		id: 'soup-not-soup',
		category: 'debate',
		left: { en: "Soup", da: "Suppe" },
		right: { en: "Not soup", da: "Ikke suppe" }
	},
	{
		id: 'petty-justified',
		category: 'debate',
		left: { en: "Petty", da: "Smålig" },
		right: { en: "Justified", da: "Berettiget" }
	},
	{
		id: 'ethical-unethical',
		category: 'debate',
		left: { en: "Ethical", da: "Etisk" },
		right: { en: "Unethical", da: "Uetisk" }
	},
	{
		id: 'classy-trashy',
		category: 'debate',
		left: { en: "Classy", da: "Stilfuld" },
		right: { en: "Trashy", da: "Tarvelig" }
	},
	{
		id: 'basic-sophisticated',
		category: 'debate',
		left: { en: "Basic", da: "Basic" },
		right: { en: "Sophisticated", da: "Sofistikeret" }
	},
	{
		id: 'overdressed-underdressed',
		category: 'debate',
		left: { en: "Overdressed", da: "Overdressed" },
		right: { en: "Underdressed", da: "Underdressed" }
	},
	{
		id: 'too-popular-not-popular-enough',
		category: 'debate',
		left: { en: "Too popular", da: "For populær" },
		right: { en: "Not popular enough", da: "Ikke populær nok" }
	},
	{
		id: 'needs-rules-better-without',
		category: 'debate',
		left: { en: "Needs rules", da: "Skal have regler" },
		right: { en: "Better without rules", da: "Bedre uden regler" }
	},
	{
		id: 'should-be-free-should-be-expensive',
		category: 'debate',
		left: { en: "Should be free", da: "Skal være gratis" },
		right: { en: "Should be expensive", da: "Skal være dyrt" }
	},
	{
		id: 'public-good-private-luxury',
		category: 'debate',
		left: { en: "Public good", da: "Fællesgode" },
		right: { en: "Private luxury", da: "Privat luksus" }
	},
	{
		id: 'real-holiday-fake-holiday',
		category: 'debate',
		left: { en: "Real holiday", da: "Rigtig helligdag" },
		right: { en: "Fake holiday", da: "Opdigtet helligdag" }
	},
	{
		id: 'good-tradition-bad-tradition',
		category: 'debate',
		left: { en: "Good tradition", da: "God tradition" },
		right: { en: "Bad tradition", da: "Dårlig tradition" }
	},
	{
		id: 'waste-of-time-time-well-spent',
		category: 'debate',
		left: { en: "Waste of time", da: "Spild af tid" },
		right: { en: "Time well spent", da: "Tid godt brugt" }
	},
	{
		id: 'immature-fun-adult-fun',
		category: 'debate',
		left: { en: "Immature fun", da: "Umoden sjov" },
		right: { en: "Adult fun", da: "Voksen sjov" }
	},
	{
		id: 'harmless-prank-cruel-prank',
		category: 'debate',
		left: { en: "Harmless prank", da: "Uskyldig spøg" },
		right: { en: "Cruel prank", da: "Grusom spøg" }
	},
	{
		id: 'good-advice-terrible-advice',
		category: 'debate',
		left: { en: "Good advice", da: "Godt råd" },
		right: { en: "Terrible advice", da: "Forfærdeligt råd" }
	},
	{
		id: 'too-niche-too-mainstream',
		category: 'debate',
		left: { en: "Too niche", da: "For niche" },
		right: { en: "Too mainstream", da: "For mainstream" }
	},
	{
		id: 'hot-cold',
		category: 'classic',
		left: { en: "Hot", da: "Varm" },
		right: { en: "Cold", da: "Kold" }
	},
	{
		id: 'fast-slow',
		category: 'classic',
		left: { en: "Fast", da: "Hurtig" },
		right: { en: "Slow", da: "Langsom" }
	},
	{
		id: 'heavy-light',
		category: 'classic',
		left: { en: "Heavy", da: "Tung" },
		right: { en: "Light", da: "Let" }
	},
	{
		id: 'loud-quiet',
		category: 'classic',
		left: { en: "Loud", da: "Høj" },
		right: { en: "Quiet", da: "Stille" }
	},
	{
		id: 'rare-common',
		category: 'classic',
		left: { en: "Rare", da: "Sjælden" },
		right: { en: "Common", da: "Almindelig" }
	},
	{
		id: 'old-fashioned-modern',
		category: 'classic',
		left: { en: "Old-fashioned", da: "Gammeldags" },
		right: { en: "Modern", da: "Moderne" }
	},
	{
		id: 'natural-artificial',
		category: 'classic',
		left: { en: "Natural", da: "Naturlig" },
		right: { en: "Artificial", da: "Kunstig" }
	},
	{
		id: 'messy-organized',
		category: 'classic',
		left: { en: "Messy", da: "Rodede" },
		right: { en: "Organized", da: "Organiseret" }
	},
	{
		id: 'flexible-rigid',
		category: 'classic',
		left: { en: "Flexible", da: "Fleksibel" },
		right: { en: "Rigid", da: "Stiv" }
	},
	{
		id: 'soft-hard',
		category: 'classic',
		left: { en: "Soft", da: "Blød" },
		right: { en: "Hard", da: "Hård" }
	},
	{
		id: 'temporary-permanent',
		category: 'classic',
		left: { en: "Temporary", da: "Midlertidig" },
		right: { en: "Permanent", da: "Permanent" }
	},
	{
		id: 'fragile-durable',
		category: 'classic',
		left: { en: "Fragile", da: "Skrøbelig" },
		right: { en: "Durable", da: "Holdbar" }
	},
	{
		id: 'local-global',
		category: 'classic',
		left: { en: "Local", da: "Lokal" },
		right: { en: "Global", da: "Global" }
	},
	{
		id: 'legal-illegal',
		category: 'classic',
		left: { en: "Legal", da: "Legal" },
		right: { en: "Illegal", da: "Ulovlig" }
	},
	{
		id: 'public-private',
		category: 'classic',
		left: { en: "Public", da: "Offentlig" },
		right: { en: "Private", da: "Privat" }
	},
	{
		id: 'formal-casual',
		category: 'classic',
		left: { en: "Formal", da: "Formel" },
		right: { en: "Casual", da: "Afslappet" }
	},
	{
		id: 'luxurious-practical',
		category: 'classic',
		left: { en: "Luxurious", da: "Luksuriøs" },
		right: { en: "Practical", da: "Praktisk" }
	},
	{
		id: 'ancient-futuristic',
		category: 'classic',
		left: { en: "Ancient", da: "Gammel" },
		right: { en: "Futuristic", da: "Futuristisk" }
	},
	{
		id: 'familiar-alien',
		category: 'classic',
		left: { en: "Familiar", da: "Velkendt" },
		right: { en: "Alien", da: "Fremmed" }
	},
	{
		id: 'safe-unsafe',
		category: 'classic',
		left: { en: "Safe", da: "Sikker" },
		right: { en: "Unsafe", da: "Usikker" }
	}
];
