name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use the latest Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Debugging - List files in build directory
        run: ls -la ./build

      - name: Debugging - Check git version and configuration
        run: |
          git --version
          git config --list
          git remote -v
          git status

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build  # Change this if your build output is in a different directory
