name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensure using the latest version compatible with Node.js 20

      - name: Setup Node.js environment
        uses: actions/setup-node@v4  # Ensure using the latest version compatible with Node.js 20
        with:
          node-version: '20'  # Use the latest Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Ensure using the latest version compatible with Node.js 20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build  # Change this if your build output is in a different directory
